version: "3.8"

services:
  db:
    image: postgres:14
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PORT=${PORT}
      - RAILS_ENV=${RAILS_ENV}
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
